version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uni-project
    env_file:
      - .env
    ports:
      - "3001:${APP_PORT}"
    restart: always
